language: c

compiler:
  - gcc

sudo: required
dist: trusty

before_install:
    - sudo apt-get install python-software-properties
    - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu/ xenial main restricted'
    - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu/ xenial main universe'
    - sudo add-apt-repository 'deb http://archive.ubuntu.com/ubuntu/ xenial main multiverse'
    - sudo apt-get update -qq
    - sudo apt-get install build-essential git-core
    - sudo apt-get install gcc-arm-linux-gnueabihf
    - sudo apt-get install qemu-user
    - sudo apt-get install python3

script:
    - make check
